## PyTorch Tutorial

IFT6135 – Representation Learning

A Deep Learning Course, January 2020

By Chin-Wei Huang 

(Adapted from Sandeep Subramanian's MILA welcome tutorial)

## 1. Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [0]:
import numpy as np
import torch

### Construct a matrix, unintialized

In [3]:
torch.Tensor(5, 3)

tensor([[2.5213e-37, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 4.6608e-32],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 2.6851e-06, 7.5632e+28]])

### Construct a randomly initialized matrix

In [4]:
# intialization
print(torch.Tensor(5, 3).uniform_(-1, 1))
# sampling
print(torch.rand(5,3)*2-1)

tensor([[-0.6599,  0.7191,  0.7249],
        [ 0.7913,  0.2766,  0.0888],
        [-0.6430, -0.5523,  0.6346],
        [ 0.9350,  0.5725, -0.0364],
        [-0.7638,  0.1039,  0.4206]])
tensor([[-0.5208, -0.0390,  0.3328],
        [ 0.6303, -0.8615,  0.0962],
        [ 0.8216, -0.5903,  0.4049],
        [ 0.6514, -0.8028, -0.2685],
        [ 0.9150, -0.7937,  0.0125]])


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

|Data type |Tensor|
|----------|------|
|32-bit floating point|	torch.float32 or torch.float|
|64-bit floating point|	torch.float64 or torch.double|
|16-bit floating point|	torch.float16 or torch.half|
|8-bit integer (unsigned)|torch.uint8|
|8-bit integer (signed)|torch.int8|
|16-bit integer (signed)|torch.int16 or torch.short|
|32-bit integer (signed)|torch.int32 or torch.int|
|64-bit integer (signed)|torch.int64 or torch.long|

### Construct a matrix filled zeros and of dtype long:

In [5]:
zeros = torch.zeros(5, 3, dtype=torch.long)
print(zeros)
print(zeros.type(), zeros.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.LongTensor torch.int64


### Creation from lists & numpy

In [7]:
# Create a tensor from list
z = torch.LongTensor([[1, 3], [2, 9]])
print(z.type(), z.dtype)
z = torch.tensor([[1, 3], [2, 9]]) # torch.tensor copies the data
print(z.type(), z.dtype)

torch.LongTensor torch.int64
torch.LongTensor torch.int64


In [9]:
# Excuse me? 
z = torch.tensor([[1, 3], [2, 9]])
print(z.dtype)
z = torch.Tensor([[1, 3], [2, 9]]) # torch.Tensor = torch.FloatTensor
print(z.dtype)
z = torch.FloatTensor([[1, 3], [2, 9]])
print(z.dtype)

z = torch.Tensor([1, 3])
print(z)
z = torch.Tensor(1, 3) # torch.Tensor = torch.empty
print(z)
z = torch.empty(1, 3)
print(z)

torch.int64
torch.float32
torch.float32
tensor([1., 3.])
tensor([[2.5215e-37, 0.0000e+00, 2.8026e-45]])
tensor([[2.5214e-37, 0.0000e+00, 2.8026e-45]])


In [12]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())
print(torch.from_numpy(np.random.rand(5, 3)).float().type())

torch.DoubleTensor
torch.FloatTensor
torch.FloatTensor


### Get its shape

In [14]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

# or your favorite np_array.shape
print(x.shape)

# dimensionality of the 0'th and 1'st axis
print(x.size(0))
print(x.shape[1])

torch.Size([5, 3])
torch.Size([5, 3])
5
3


### Simple mathematical operations

In [16]:
power = torch.randn(5, 3)
y = torch.abs(x) ** power
print(y)

tensor([[0.8835, 1.2475, 8.1072],
        [1.4861, 0.9235, 0.4020],
        [1.2223, 1.5488, 0.9635],
        [0.0531, 0.6477, 0.8946],
        [1.3213, 1.0643, 0.5796]])


In [17]:
noise = torch.randn(5, 3)
y = x / torch.sqrt(noise ** 2)
# equal to torch.abs
y_ = x / torch.abs(noise)

print(y)
print(y_)

tensor([[ 2.1399,  1.5251, -0.7141],
        [ 1.7063, -0.7511,  1.2147],
        [-0.5401, -0.3802,  2.5490],
        [-0.0649,  0.1416, -1.1374],
        [ 1.3033,  0.5903,  0.4183]])
tensor([[ 2.1399,  1.5251, -0.7141],
        [ 1.7063, -0.7511,  1.2147],
        [-0.5401, -0.3802,  2.5490],
        [-0.0649,  0.1416, -1.1374],
        [ 1.3033,  0.5903,  0.4183]])


### Broadcasting

In [18]:
x = torch.ones(5,3)
print(x.size())
print(x)
print()

print('Broadcast along rows')
y = x + torch.arange(3) 
print(y)
print()

print('Broadcast along columns')
y = x + torch.arange(5).view(5,1)
print(y)
y = x + torch.arange(5)[:,None]
print(y)
print()


# size mismatch!
print(x + torch.arange(5))

torch.Size([5, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Broadcast along rows
tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

Broadcast along columns
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.]])



RuntimeError: ignored

<font color='blue'>(exercise)</font>

In [19]:
x = torch.arange(5)
# Q: get the following matrix from x
# [[0, 1, 2, 3, 4],
#  [1, 2, 3, 4, 5],
#  [2, 3, 4, 5, 6],
#  [3, 4, 5, 6, 7],
#  [4, 5, 6, 7, 8]]

print(x[None,:] + x[:,None])


tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]])


### Reshape

In [23]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1. 
print(y.view(-1, 15).unsqueeze(1).unsqueeze(2).unsqueeze(3).squeeze().size())
# If input is of shape: (Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


### Repeat

In [78]:
y = torch.randn(50, 15)
print(y.unsqueeze(1).expand(50, 100, 15).size())
print(y.unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())
# don't confuse it with tensor.repeat ...
print(y.unsqueeze(1).repeat(50,100,1).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])
torch.Size([2500, 100, 15])


### Concatenate

In [26]:
y = torch.randn(5, 10, 15)
# 2 is the dimension over which the tensors are concatenated
print(torch.cat([y, y], 2).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

torch.Size([5, 10, 30])
torch.Size([2, 5, 10, 15])


<font color='blue'>(exercise)</font>

In [27]:
# Q: how to do torch.stack using cat?
print(torch.cat([y.unsqueeze(0), y[None]], 0).size())

torch.Size([2, 5, 10, 15])


### Advanced Indexing

In [30]:
y = torch.randn(2, 3, 4)
print(y[[1, 0, 1, 1]].size())


# PyTorch doesn't support negative strides yet so ::-1 does not work.
rev_idx = torch.arange(1, -1, -1).long()
print(rev_idx)
print(y[rev_idx].size()) # y[rev_idx] - y[[1,0]] should be all zeros

print()

# gather(input, dim, index)
v = torch.arange(12).view(3,4)
print(v.shape)
print(v)
# [0,1,2,3]
# [4,5,6,7]
# [8,9,10,11]
# want to return [1,6,8]

print(torch.gather(v, 1, torch.tensor([1,2,0]).long().unsqueeze(1))) # .float will fail

torch.Size([4, 3, 4])
tensor([1, 0])
torch.Size([2, 3, 4])

torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[1],
        [6],
        [8]])


<font color='blue'>(exercise)</font>

In [35]:
v = torch.arange(12).view(3,4)
# [0,1,2,3]
# [4,5,6,7]
# [8,9,10,11]
# Q: get [0, 5, 10, 3] from v

print(torch.gather(v, 0, torch.tensor([0,1,2,0]).long()[None,:])) # .float will fail

tensor([[ 0,  5, 10,  3]])


### Contiguity in memory

In [38]:
# The following PyTorch operations change the meta data of the tensor 
# instead of creating a new tensor:
#     .view, .transpose, .permute, .expand, .narrow (for higher dim indexing)

x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)

print('Contiguity : %s ' % (x.is_contiguous()))
x = x.unsqueeze(0).expand(30, 5, 3)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.contiguous()
print('Contiguity : %s ' % (x.is_contiguous()))


tensor([[ 0.2748,  0.7930,  0.8974],
        [ 0.7964, -0.9919, -0.0291],
        [-0.7532, -0.3638,  0.8723],
        [-0.2218, -0.2935,  0.8532],
        [ 0.4569, -0.7422, -0.8888]])
Contiguity : True 
Contiguity : False 
Contiguity : True 


<font color='blue'>(exercise)</font>

In [151]:
x = torch.arange(9).view(3,3)
print(x)
# Q: get [0, 3, 6, 1, 4, 7, 2, 5, 8] from x using transpose and view


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
